name: k_chart_plus
description: A Flutter K Chart.
version: 0.7.0
homepage: https://github.com/TrangLeQuynh/k_chart_plus

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
