name: k_chart_plus
summary: A Flutter charting library with a candle chart and depth chart.
description: A Flutter charting library with candle chart(with custom indicators) and depth chart
version: 2.0.1
homepage: https://github.com/KevlarTheGreat/k_chart_plus

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
